---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc


homebrew_prefix: /opt/homebrew # /usr/local [default] for macOS Intel, /opt/homebrew for Apple Silicon

homebrew_installed_packages: # - ansible # Installed via Pip.
  - autoconf
  - baobab # disk usage analyzer
  - bash-completion
  - erlang
  - gettext
  - gifsicle
  - git
  - gh
  - glab
  - go
  - gpg
  - htop
  - httpie
  - hugo
  - imagemagick
  - iperf
  - jq
  - libevent
  - pandoc
  - sqlite
  - mcrypt
  - nethogs
  - nmap
  - node
  - nvm
  - p7zip
  - ssh-copy-id
  - cowsay
  - readline
  - terraform
  - tmux
  - thefuck
  - openssl
  - pv
  - webp
  - wget
  - wrk

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - authy
  - bitwarden
  - calibre
  - chromedriver
  - darktable
  - docker
  - digikam
  - dropbox
  - figma
  - firefox
  - gimp
  - google-chrome
  - google-drive-file-stream
  - google-photos-backup-and-sync
  - handbrake
  - inkscape
  - libreoffice
  - licecap
  - postman
  - sequel-pro
  - signal
  - spotify
  - sublime-text
  - thunderbird
  - visual-studio-code
  - vlc

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: lerna
  - name: firebase-tools
  - name: webpack
  - name: webpack-cli
  - name: eslint
  - name: sqip


# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
